export const APP_CONFIG = {
  renderer: {
    clearColor: 0x000000,
    maxPixelRatio: 2,
    toneMappingExposure: 0.94,
  },
  camera: {
    fov: 35,
    closeFov: 14,
    near: 0.002,
    far: 160,
    initialPosition: [0.35, 0.24, 4.9],
  },
  controls: {
    minDistance: 1.004,
    maxDistance: 8.5,
    rotateSpeed: 0.72,
    zoomSpeed: 1.1,
    closeRotateSpeed: 0.02,
    closeZoomSpeed: 0.5,
    dampingFactor: 0.07,
    closeDampingFactor: 0.12,
    precisionRampDistance: 1.42,
    rotatePrecisionExponent: 1.65,
    touchRotateFactor: 0.7,
    closeTouchRotateFactor: 0.4,
    penRotateFactor: 0.82,
    touchReferenceHeight: 900,
    touchMinViewportFactor: 0.56,
    minPolarAngle: 0.12,
    maxPolarAngle: Math.PI - 0.12,
  },
  earth: {
    tiltDegrees: -23.5,
    surfaceRotationDegrees: 210,
    radius: 1,
    cloudRadius: 1.016,
    atmosphereRadius: 1.05,
    geometrySegments: 128,
  },
  detail: {
    fadeDistance: 2.35,
  },
  flights: {
    openSkyStatesUrl: "https://opensky-network.org/api/states/all",
    markerBaseRadius: 1.045,
    markerAltitudeScale: 0.03,
    markerMinSize: 0.008,
    markerMaxSize: 0.018,
  },
  ships: {
    snapshotUrl: "/api/ships",
    markerBaseRadius: 1.006,
    markerMinSize: 0.01,
    markerMaxSize: 0.016,
  },
  locationLog: {
    snapshotUrl: "/api/mylocations",
    markerBaseRadius: 1.026,
    markerMinSize: 0.01,
    markerMaxSize: 0.024,
    markerMinScreenSize: 7,
    markerMaxScreenSize: 20,
    latestMarkerMinSize: 0.02,
    latestMarkerMaxSize: 0.046,
    latestMarkerMinScreenSize: 16,
    latestMarkerMaxScreenSize: 46,
    trailRadius: 1.024,
    trailOpacity: 0.42,
    focusPaddingDegrees: 0.32,
    focusMinDistance: 1.006,
    focusMaxDistance: 2.5,
    focusSingleDistance: 1.012,
    focusDurationMs: 1450,
  },
  mapStyle: {
    defaultMode: "terrain",
  },
  trafficInfo: {
    compactBreakpoint: 760,
    defaultMode: "detail",
    dragThreshold: 10,
    mobileDefaultMode: "simple",
  },
  search: {
    geocodeUrl: "/api/geocode",
    focusDistance: 1.04,
    moveDurationMs: 980,
    resultLimit: 5,
  },
  regionalTexture: {
    activationDistance: 1.28,
    keepMargin: 0.16,
    requestSize: 2048,
    minRadius: 0.07,
    maxRadius: 7.4,
    maxLongitudeRadius: 5.4,
    snapRatio: 0.38,
    minSnapStep: 0.025,
    minSpan: 0.025,
    styles: {
      terrain: {
        url: "https://ows.terrestris.de/osm/service",
        layer: "OSM-Overlay-WMS",
        format: "image/png",
        opacity: 0.9,
        transparent: true,
      },
      simplified: {
        url: "https://ows.terrestris.de/osm/service",
        layer: "OSM-WMS",
        format: "image/png",
        opacity: 1,
        transparent: false,
      },
    },
  },
};
